services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-app_mysql_data:/var/lib/mysql
    networks:
      - app-network

  springboot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        TIMEOUT: 3600
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
    depends_on:
      - mysql
    networks:
      - app-network

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-app
    volumes:
      - ./frontend/nginx-react.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  mysql-app_mysql_data:

networks:
  app-network:
    driver: bridge